import { PullRequest } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600000).toISOString();
const days = (d: number, extraH = 0) =>
  new Date(now - (d * 86400000 + extraH * 3600000)).toISOString();

export const MOCK_PRS: PullRequest[] = [
  {
    id: "gh-1",
    title: "feat: implement OAuth2 PKCE flow for mobile clients",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "github",
    repo: "ndg/auth-service",
    status: "approved",
    reviewers: ["Marcus Webb", "Priya Patel"],
    createdAt: days(1, 3),
    updatedAt: hours(2),
    sourceBranch: "feat/oauth2-pkce",
    targetBranch: "main",
    ageDays: 1,
  },
  {
    id: "gl-1",
    title: "fix: resolve N+1 query in project listing endpoint",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "open",
    reviewers: ["Sarah Chen"],
    createdAt: days(0, 6),
    updatedAt: hours(1),
    sourceBranch: "fix/n-plus-one-projects",
    targetBranch: "develop",
    ageDays: 0,
  },
  {
    id: "bb-1",
    title: "chore: migrate CI pipeline to parallel test execution",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/infrastructure",
    status: "changes_requested",
    reviewers: ["Jake Morrison"],
    createdAt: days(5),
    updatedAt: days(1),
    sourceBranch: "chore/parallel-ci",
    targetBranch: "main",
    ageDays: 5,
  },
  {
    id: "gh-2",
    title: "feat: add real-time WebSocket notifications for PR reviews",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "github",
    repo: "ndg/notifications",
    status: "open",
    reviewers: ["Priya Patel", "Sarah Chen"],
    createdAt: days(3),
    updatedAt: days(0, 8),
    sourceBranch: "feat/ws-notifications",
    targetBranch: "main",
    ageDays: 3,
  },
  {
    id: "gl-2",
    title: "refactor: extract shared validation middleware",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "approved",
    reviewers: ["Marcus Webb"],
    createdAt: days(2),
    updatedAt: hours(5),
    sourceBranch: "refactor/validation-middleware",
    targetBranch: "develop",
    ageDays: 2,
  },
  {
    id: "bb-2",
    title: "feat: add Datadog APM tracing to all microservices",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/observability",
    status: "open",
    reviewers: ["Jake Morrison"],
    createdAt: days(7, 2),
    updatedAt: days(2),
    sourceBranch: "feat/datadog-apm",
    targetBranch: "main",
    ageDays: 7,
  },
  {
    id: "gh-3",
    title: "fix: handle edge case in timezone conversion for scheduled jobs",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "github",
    repo: "ndg/scheduler",
    status: "changes_requested",
    reviewers: ["Sarah Chen"],
    createdAt: days(4),
    updatedAt: days(0, 3),
    sourceBranch: "fix/tz-edge-case",
    targetBranch: "main",
    ageDays: 4,
  },
  {
    id: "gl-3",
    title: "docs: update API reference with v3 breaking changes",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "gitlab",
    repo: "ndg/docs",
    status: "open",
    reviewers: [],
    createdAt: days(0, 2),
    updatedAt: hours(1),
    sourceBranch: "docs/v3-api-reference",
    targetBranch: "main",
    ageDays: 0,
  },
  {
    id: "gh-4",
    title: "perf: optimize image processing pipeline with worker threads",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "github",
    repo: "ndg/media-service",
    status: "open",
    reviewers: ["Priya Patel"],
    createdAt: days(10),
    updatedAt: days(3),
    sourceBranch: "perf/worker-threads-images",
    targetBranch: "main",
    ageDays: 10,
  },
  {
    id: "bb-3",
    title: "feat: implement SSO with Azure AD for enterprise clients",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/auth-service",
    status: "approved",
    reviewers: ["Marcus Webb", "Jake Morrison"],
    createdAt: days(2, 5),
    updatedAt: hours(8),
    sourceBranch: "feat/azure-ad-sso",
    targetBranch: "main",
    ageDays: 2,
  },
];
