import { PullRequest } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600000).toISOString();
const days = (d: number, extraH = 0) =>
  new Date(now - (d * 86400000 + extraH * 3600000)).toISOString();

export const MOCK_PRS: PullRequest[] = [
  {
    id: "gh-1",
    title: "feat: implement OAuth2 PKCE flow for mobile clients",
    description: "This PR implements the OAuth2 PKCE (Proof Key for Code Exchange) flow for our mobile clients. It includes token refresh logic, secure storage integration, and comprehensive error handling for network failures during the auth flow.",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "github",
    repo: "ndg/auth-service",
    status: "approved",
    reviewers: ["Marcus Webb", "Priya Patel"],
    reviewerDetails: [
      { name: "Marcus Webb", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus", status: "approved" },
      { name: "Priya Patel", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya", status: "approved" },
    ],
    createdAt: days(1, 3),
    updatedAt: hours(2),
    reviewRequestedAt: days(1, 2),
    sourceBranch: "feat/oauth2-pkce",
    targetBranch: "main",
    ageDays: 1,
    ciStatus: "success",
    labels: ["feature", "auth", "mobile"],
  },
  {
    id: "gl-1",
    title: "fix: resolve N+1 query in project listing endpoint",
    description: "Fixes the N+1 query problem in the /projects endpoint by using eager loading with includes. Benchmarks show 85% reduction in query count and 3x faster response times.",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "open",
    reviewers: ["Sarah Chen"],
    reviewerDetails: [
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "pending" },
    ],
    createdAt: days(0, 6),
    updatedAt: hours(1),
    reviewRequestedAt: days(0, 5),
    sourceBranch: "fix/n-plus-one-projects",
    targetBranch: "develop",
    ageDays: 0,
    ciStatus: "success",
    labels: ["bug", "performance"],
  },
  {
    id: "bb-1",
    title: "chore: migrate CI pipeline to parallel test execution",
    description: "Migrates our CI pipeline to use parallel test execution across 4 workers. Expected build time reduction from 18min to ~6min. Includes sharding configuration and test result aggregation.",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/infrastructure",
    status: "changes_requested",
    reviewers: ["Jake Morrison"],
    reviewerDetails: [
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "changes_requested" },
    ],
    createdAt: days(5),
    updatedAt: days(1),
    reviewRequestedAt: days(4, 20),
    sourceBranch: "chore/parallel-ci",
    targetBranch: "main",
    ageDays: 5,
    ciStatus: "failure",
    labels: ["chore", "ci"],
  },
  {
    id: "gh-2",
    title: "feat: add real-time WebSocket notifications for PR reviews",
    description: "Implements WebSocket-based real-time notifications when PRs receive reviews, comments, or status changes. Uses Redis pub/sub for horizontal scaling across multiple server instances.",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "github",
    repo: "ndg/notifications",
    status: "open",
    reviewers: ["Priya Patel", "Sarah Chen"],
    reviewerDetails: [
      { name: "Priya Patel", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya", status: "commented" },
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "pending" },
    ],
    createdAt: days(3),
    updatedAt: days(0, 8),
    reviewRequestedAt: days(2, 20),
    sourceBranch: "feat/ws-notifications",
    targetBranch: "main",
    ageDays: 3,
    ciStatus: "running",
    labels: ["feature", "real-time"],
  },
  {
    id: "gl-2",
    title: "refactor: extract shared validation middleware",
    description: "Extracts common request validation logic into a shared middleware package. Reduces code duplication across 12 services and ensures consistent error response format.",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "approved",
    reviewers: ["Marcus Webb"],
    reviewerDetails: [
      { name: "Marcus Webb", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus", status: "approved" },
    ],
    createdAt: days(2),
    updatedAt: hours(5),
    reviewRequestedAt: days(1, 20),
    sourceBranch: "refactor/validation-middleware",
    targetBranch: "develop",
    ageDays: 2,
    ciStatus: "success",
    labels: ["refactor"],
  },
  {
    id: "bb-2",
    title: "feat: add Datadog APM tracing to all microservices",
    description: "Adds Datadog APM distributed tracing to all 8 microservices. Includes custom span annotations for database queries, HTTP calls, and queue operations. Configurable sampling rate per environment.",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/observability",
    status: "open",
    reviewers: ["Jake Morrison"],
    reviewerDetails: [
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "pending" },
    ],
    createdAt: days(7, 2),
    updatedAt: days(2),
    reviewRequestedAt: days(7),
    sourceBranch: "feat/datadog-apm",
    targetBranch: "main",
    ageDays: 7,
    ciStatus: "success",
    labels: ["feature", "observability"],
  },
  {
    id: "gh-3",
    title: "fix: handle edge case in timezone conversion for scheduled jobs",
    description: "Fixes a bug where scheduled jobs crossing DST boundaries would either skip or double-execute. Now uses UTC internally and converts only at display time.",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "github",
    repo: "ndg/scheduler",
    status: "changes_requested",
    reviewers: ["Sarah Chen"],
    reviewerDetails: [
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "changes_requested" },
    ],
    createdAt: days(4),
    updatedAt: days(0, 3),
    reviewRequestedAt: days(3, 18),
    sourceBranch: "fix/tz-edge-case",
    targetBranch: "main",
    ageDays: 4,
    ciStatus: "failure",
    labels: ["bug", "scheduler"],
  },
  {
    id: "gl-3",
    title: "docs: update API reference with v3 breaking changes",
    description: "Updates the API reference documentation to reflect all breaking changes in v3. Includes migration guide, deprecated endpoint mapping, and new authentication requirements.",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "gitlab",
    repo: "ndg/docs",
    status: "open",
    reviewers: [],
    reviewerDetails: [],
    createdAt: days(0, 2),
    updatedAt: hours(1),
    sourceBranch: "docs/v3-api-reference",
    targetBranch: "main",
    ageDays: 0,
    ciStatus: "pending",
    labels: ["docs"],
  },
  {
    id: "gh-4",
    title: "perf: optimize image processing pipeline with worker threads",
    description: "Moves image processing (resize, compress, format conversion) to worker threads. Benchmarks show 4x throughput improvement on 8-core machines. Includes graceful degradation for single-core environments.",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "github",
    repo: "ndg/media-service",
    status: "open",
    reviewers: ["Priya Patel"],
    reviewerDetails: [
      { name: "Priya Patel", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya", status: "pending" },
    ],
    createdAt: days(10),
    updatedAt: days(3),
    reviewRequestedAt: days(9, 12),
    sourceBranch: "perf/worker-threads-images",
    targetBranch: "main",
    ageDays: 10,
    ciStatus: "success",
    labels: ["performance", "media"],
  },
  {
    id: "bb-3",
    title: "feat: implement SSO with Azure AD for enterprise clients",
    description: "Implements SAML-based SSO integration with Azure AD for enterprise tier clients. Includes automatic user provisioning via SCIM, role mapping configuration, and admin dashboard for SSO management.",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/auth-service",
    status: "approved",
    reviewers: ["Marcus Webb", "Jake Morrison"],
    reviewerDetails: [
      { name: "Marcus Webb", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus", status: "approved" },
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "approved" },
    ],
    createdAt: days(2, 5),
    updatedAt: hours(8),
    reviewRequestedAt: days(2, 3),
    sourceBranch: "feat/azure-ad-sso",
    targetBranch: "main",
    ageDays: 2,
    ciStatus: "success",
    labels: ["feature", "auth", "enterprise"],
  },
];
