import { PullRequest } from "./types";

const now = Date.now();
const mins = (m: number) => new Date(now - m * 60000).toISOString();
const hours = (h: number) => new Date(now - h * 3600000).toISOString();
const days = (d: number, extraH = 0) =>
  new Date(now - (d * 86400000 + extraH * 3600000)).toISOString();

export const MOCK_PRS: PullRequest[] = [
  {
    id: "gl-1",
    title: "fix: resolve N+1 query in project listing endpoint",
    description: "Fixes the N+1 query problem in the /projects endpoint by using eager loading with includes. Benchmarks show 85% reduction in query count and 3x faster response times.",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "open",
    reviewers: ["Sarah Chen"],
    reviewerDetails: [
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "pending" },
    ],
    createdAt: mins(25),
    updatedAt: mins(10),
    reviewRequestedAt: mins(20),
    sourceBranch: "fix/n-plus-one-projects",
    targetBranch: "develop",
    ageDays: 0,
    ciStatus: "success",
    labels: ["bug", "performance"],
  },
  {
    id: "bb-1",
    title: "chore: migrate CI pipeline to parallel test execution",
    description: "Migrates our CI pipeline to use parallel test execution across 4 workers. Expected build time reduction from 18min to ~6min.",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/infrastructure",
    status: "changes_requested",
    reviewers: ["Jake Morrison"],
    reviewerDetails: [
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "changes_requested" },
    ],
    createdAt: days(5),
    updatedAt: days(1),
    reviewRequestedAt: days(4, 20),
    sourceBranch: "chore/parallel-ci",
    targetBranch: "main",
    ageDays: 5,
    ciStatus: "failure",
    labels: ["chore", "ci"],
  },
  {
    id: "gl-2",
    title: "refactor: extract shared validation middleware",
    description: "Extracts common request validation logic into a shared middleware package. Reduces code duplication across 12 services.",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "gitlab",
    repo: "ndg/api-gateway",
    status: "approved",
    reviewers: ["Marcus Webb"],
    reviewerDetails: [
      { name: "Marcus Webb", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus", status: "approved" },
    ],
    createdAt: hours(3),
    updatedAt: hours(1),
    reviewRequestedAt: hours(2),
    sourceBranch: "refactor/validation-middleware",
    targetBranch: "develop",
    ageDays: 0,
    ciStatus: "success",
    labels: ["refactor"],
  },
  {
    id: "bb-2",
    title: "feat: add Datadog APM tracing to all microservices",
    description: "Adds Datadog APM distributed tracing to all 8 microservices. Includes custom span annotations for database queries, HTTP calls, and queue operations.",
    author: "Marcus Webb",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/observability",
    status: "open",
    reviewers: ["Jake Morrison"],
    reviewerDetails: [
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "pending" },
    ],
    createdAt: days(10),
    updatedAt: days(3),
    reviewRequestedAt: days(9, 12),
    sourceBranch: "feat/datadog-apm",
    targetBranch: "main",
    ageDays: 10,
    ciStatus: "success",
    labels: ["feature", "observability"],
  },
  {
    id: "gl-3",
    title: "docs: update API reference with v3 breaking changes",
    description: "Updates the API reference documentation to reflect all breaking changes in v3. Includes migration guide and deprecated endpoint mapping.",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "gitlab",
    repo: "ndg/docs",
    status: "open",
    reviewers: [],
    reviewerDetails: [],
    createdAt: mins(45),
    updatedAt: mins(15),
    sourceBranch: "docs/v3-api-reference",
    targetBranch: "main",
    ageDays: 0,
    ciStatus: "pending",
    labels: ["docs"],
  },
  {
    id: "bb-3",
    title: "feat: implement SSO with Azure AD for enterprise clients",
    description: "Implements SAML-based SSO integration with Azure AD for enterprise tier clients. Includes automatic user provisioning via SCIM.",
    author: "Sarah Chen",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/auth-service",
    status: "approved",
    reviewers: ["Marcus Webb", "Jake Morrison"],
    reviewerDetails: [
      { name: "Marcus Webb", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=marcus", status: "approved" },
      { name: "Jake Morrison", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake", status: "approved" },
    ],
    createdAt: days(2, 5),
    updatedAt: hours(8),
    reviewRequestedAt: days(2, 3),
    sourceBranch: "feat/azure-ad-sso",
    targetBranch: "main",
    ageDays: 2,
    ciStatus: "success",
    labels: ["feature", "auth", "enterprise"],
  },
  {
    id: "gl-4",
    title: "fix: handle edge case in timezone conversion for scheduled jobs",
    description: "Fixes a bug where scheduled jobs crossing DST boundaries would either skip or double-execute.",
    author: "Priya Patel",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya",
    url: "#",
    platform: "gitlab",
    repo: "ndg/scheduler",
    status: "changes_requested",
    reviewers: ["Sarah Chen"],
    reviewerDetails: [
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "changes_requested" },
    ],
    createdAt: days(4),
    updatedAt: hours(3),
    reviewRequestedAt: days(3, 18),
    sourceBranch: "fix/tz-edge-case",
    targetBranch: "main",
    ageDays: 4,
    ciStatus: "failure",
    labels: ["bug", "scheduler"],
  },
  {
    id: "bb-4",
    title: "feat: add real-time WebSocket notifications for PR reviews",
    description: "Implements WebSocket-based real-time notifications when PRs receive reviews, comments, or status changes.",
    author: "Jake Morrison",
    authorAvatar: "https://api.dicebear.com/9.x/notionists/svg?seed=jake",
    url: "#",
    platform: "bitbucket",
    repo: "ndg/notifications",
    status: "open",
    reviewers: ["Priya Patel", "Sarah Chen"],
    reviewerDetails: [
      { name: "Priya Patel", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=priya", status: "commented" },
      { name: "Sarah Chen", avatar: "https://api.dicebear.com/9.x/notionists/svg?seed=sarah", status: "pending" },
    ],
    createdAt: hours(7),
    updatedAt: hours(2),
    reviewRequestedAt: hours(6),
    sourceBranch: "feat/ws-notifications",
    targetBranch: "main",
    ageDays: 0,
    ciStatus: "running",
    labels: ["feature", "real-time"],
  },
];
